config/routes.rb
Rails.application.routes.draw do
  resources :pressreleases
  resources :locations
  resources :headlines
  resources :calendars
  
  resources :home
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  

   root :to => 'home#index'

end

app/controllers/pressreleases_controller.rb
class PressreleasesController < ApplicationController
  before_action :set_pressrelease, only: [:show, :edit, :update, :destroy]

  # GET /pressreleases
  # GET /pressreleases.json
  def index
    @pressreleases = Pressrelease.all
  end

  # GET /pressreleases/1
  # GET /pressreleases/1.json
  def show
    @pressrelease = Pressrelease.find(params[:id])
    send_data @pressrelease.file_contents, :filename => @pressrelease.filename, :type => @pressrelease.content_type
  end

  # GET /pressreleases/new
  def new
    @pressrelease = Pressrelease.new
  end

  # GET /pressreleases/1/edit
  def edit
  end

  # POST /pressreleases
  # POST /pressreleases.json
  def create
    @pressrelease = Pressrelease.new(pressrelease_params)

    respond_to do |format|
      if @pressrelease.save
        format.html { redirect_to @pressrelease, notice: 'Press Release was successfully saved.' }
        format.json { render :show, status: :created, location: @pressrelease }
      else
        format.html { render :new }
        format.json { render json: @pressrelease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pressreleases/1
  # PATCH/PUT /pressreleases/1.json
  def update
    respond_to do |format|
      if @pressrelease.update(pressrelease_params)
        format.html { redirect_to @pressrelease, notice: 'Press Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @pressrelease }
      else
        format.html { render :edit }
        format.json { render json: @pressrelease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pressreleases/1
  # DELETE /pressreleases/1.json
  def destroy
    @pressrelease.destroy
    respond_to do |format|
      format.html { redirect_to pressreleases_url, notice: 'Press Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pressrelease
      @pressrelease = Pressrelease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pressrelease_params
      params.require(:pressrelease).permit(:filename, :content_type, :file_contents, :file)
    end
    

end

app/helpers/pressreleases_helper.rb
module PressreleasesHelper
end

app/views/pressreleases/_form.html.erb
<%= form_for(@pressrelease) do |f| %>
  <% if @pressrelease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pressrelease.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @pressrelease.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pressreleases/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<h1>Edit Press Release</h1>

<%= render 'form' %>

<%= link_to 'Show', @pressrelease %> |
<%= link_to 'Back', pressreleases_path %>
</div>
</div>
</div>

app/views/pressreleases/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<p id="notice"><%= notice %></p>

<h1>Press Releases</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Filename</th>
      <th>Content type</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pressreleases.each do |pressrelease| %>
      <tr>
        <td><%= pressrelease.created_at %></td>
        <td><%= pressrelease.filename %></td>
        <td><%= pressrelease.content_type %></td>
        
        <td><%= link_to 'Show', pressrelease %></td>
        <td><%= link_to 'Edit', edit_pressrelease_path(pressrelease) %></td>
        <td><%= link_to 'Destroy', pressrelease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Press Release', new_pressrelease_path %>
</div>
</div>
</div>

app/views/pressreleases/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<h1>Add A Press Release</h1>

<%= render 'form' %>

<%= link_to 'Back', pressreleases_path %>
</div>
</div>
</div>

app/views/pressreleases/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @pressrelease.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @pressrelease.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @pressrelease.file_contents %>
</p>

<%= link_to 'Edit', edit_pressrelease_path(@pressrelease) %> |
<%= link_to 'Back', pressreleases_path %>
</div>
</div>
</div>