config/routes.rb
Rails.application.routes.draw do
  resources :pressreleases
  resources :locations
  resources :headlines
  resources :calendars
  
  resources :home
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  

   root :to => 'home#index'

end

app/models/headline.rb
class Headline < ActiveRecord::Base
  
  default_scope { order('created_at DESC') }
  
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
  before_action :set_headline, only: [:show, :edit, :update, :destroy]

  # GET /headlines
  # GET /headlines.json
  def index
    @headlines = Headline.all
  end

  # GET /headlines/1
  # GET /headlines/1.json
  def show
  end

  # GET /headlines/new
  def new
    @headline = Headline.new
  end

  # GET /headlines/1/edit
  def edit
  end

  # POST /headlines
  # POST /headlines.json
  def create
    @headline = Headline.new(headline_params)

    respond_to do |format|
      if @headline.save
        format.html { redirect_to @headline, notice: 'Headline was successfully created.' }
        format.json { render :show, status: :created, location: @headline }
      else
        format.html { render :new }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headlines/1
  # PATCH/PUT /headlines/1.json
  def update
    respond_to do |format|
      if @headline.update(headline_params)
        format.html { redirect_to @headline, notice: 'Headline was successfully updated.' }
        format.json { respond_with_bip(@headline) }
      else
        format.html { render :edit }
         format.json { respond_with_bip(@headline) }
      end
    end
  end

  # DELETE /headlines/1
  # DELETE /headlines/1.json
  def destroy
    @headline.destroy
    respond_to do |format|
      format.html { redirect_to headlines_url, notice: 'Headline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_headline
      @headline = Headline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def headline_params
      params.require(:headline).permit(:leadtext, :display, :url)
    end
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
  

  
end

app/views/headlines/_form.html.erb
<%= form_for(@headline) do |f| %>
  <% if @headline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@headline.errors.count, "error") %> prohibited this headline from being saved:</h2>

      <ul>
      <% @headline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :leadtext %><br>
    <%= f.text_area :leadtext %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.url_field :url %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.check_box :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/headlines/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<h1>Edit Headline</h1>

<%= render 'form' %>

<%= link_to 'Show', @headline %> |
<%= link_to 'Back', headlines_path %>
</div>
</div>
</div>

app/views/headlines/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<p id="notice"><%= notice %></p>

<h1>Headlines</h1>

<table>
  <thead>
    <tr>
      <th>Leadtext</th>
       <th>Link URL</th>
      <th>Display?</th>
       <th>Created</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @headlines.each do |headline| %>
      <tr>
        <td><%= headline.leadtext %></td>
        <td><%= headline.url %></td>
       <td><center><i><%= best_in_place headline, :display, :type => :checkbox, :nil => "?" %></i></center></td>
        <td><%= headline.created_at %></td>
        <td><%= link_to 'Show', headline %></td>
        <td><%= link_to 'Edit', edit_headline_path(headline) %></td>
        <td><%= link_to 'Destroy', headline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Headline', new_headline_path %>
</div>
</div>
</div>

app/views/headlines/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<h1>New Headline</h1>

<%= render 'form' %>

<%= link_to 'Back', headlines_path %>
</div>
</div>
</div>

app/views/headlines/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<br><br>
<br><br>
<br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Leadtext:</strong>
  <%= @headline.leadtext %>
</p>

<p>
  <strong>Url</strong>
  <%= @headline.url %>
</p>

<p>
  <strong>Display:</strong>
  <%= @headline.display %>
</p>

<%= link_to 'Edit', edit_headline_path(@headline) %> |
<%= link_to 'Back', headlines_path %>
</div>
</div>
</div>